packages:
  - frontend
  - backend

allowBuilds:
  prisma: true
  '@prisma/engines': true
  '@prisma/client': true
  '@scarf/scarf': false

minimumReleaseAgeExclude:
  - '@fastify/static@10.1.4'
  - '@nestjs/cli@12.0.3'
  - '@tanstack/query-core@5.103.1'
  - '@tanstack/react-query@5.103.1'
